add crawler javday for 国产
sqzw-x/mdcx pull request #172
Opened 2024-04-18 16:12 UTC by xsxiaosa

新增站点 https://javday.tv/ 适配国产适配刮削

2024-05-22 07:44 UTC, sqzw-x requested changes

2024-05-22 07:44 UTC, sqzw-x commented on src/views/MDCx.py
> +        self.comboBox_website_all.setItemText(33, _translate("MDCx", "javday"))
修改 ui 文件而不是此文件. 此文件由 ui 文件编译而来

2024-05-26 05:08 UTC, xsxiaosa commented
已修改UI文件

2024-05-27 11:44 UTC, merged

2024-05-30 12:57 UTC, anyingxiuluo commented
这个pr会导致命名-分辨率获取方式选择使用路径中包含的画质信息时出现报错，导致所有的刮削都显示失败，望优化。
![微信截图_20240530203750](https://github.com/sqzw-x/mdcx/assets/125189022/1319b72f-19ca-41b8-98f6-adfac2dbed2f)

2024-06-01 08:34 UTC, xsxiaosa commented
> 这个pr会导致命名-分辨率获取方式选择使用路径中包含的画质信息时出现报错，导致所有的刮削都显示失败，望优化。 ![微信截图_20240530203750](https://private-user-images.githubusercontent.com/125189022/335187667-1319b72f-19ca-41b8-98f6-adfac2dbed2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzExNjAsIm5iZiI6MTcxNzIzMDg2MCwicGF0aCI6Ii8xMjUxODkwMjIvMzM1MTg3NjY3LTEzMTliNzJmLTE5Y2EtNDFiOC05OGY2LWFkZmFjMmRiZWQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwODM0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDc5YzBhZmVkYmRkMDZiMTA5NjFlM2YxMmZlN2IyM2U3ZjFjNzVkMjFhYmJhMmE4ZTU3MzIwMGExNTgxYWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9K_9t2kELMOvjYM5DOFBjekdTERZ3i9hBNGPsk7rPBs)

https://github.com/xsxiaosa/mdcx/releases/tag/daily_release 最近不方便测试,你可以先下这个试下是否正常

2024-06-01 09:10 UTC, anyingxiuluo commented
> > 这个pr会导致命名-分辨率获取方式选择使用路径中包含的画质信息时出现报错，导致所有的刮削都显示失败，望优化。 ![微信截图_20240530203750](https://private-user-images.githubusercontent.com/125189022/335187667-1319b72f-19ca-41b8-98f6-adfac2dbed2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzExNjAsIm5iZiI6MTcxNzIzMDg2MCwicGF0aCI6Ii8xMjUxODkwMjIvMzM1MTg3NjY3LTEzMTliNzJmLTE5Y2EtNDFiOC05OGY2LWFkZmFjMmRiZWQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwODM0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDc5YzBhZmVkYmRkMDZiMTA5NjFlM2YxMmZlN2IyM2U3ZjFjNzVkMjFhYmJhMmE4ZTU3MzIwMGExNTgxYWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9K_9t2kELMOvjYM5DOFBjekdTERZ3i9hBNGPsk7rPBs)
> 
> https://github.com/xsxiaosa/mdcx/releases/tag/daily_release 最近不方便测试,你可以先下这个试下是否正常

这个可以了

2024-07-16 01:40 UTC, anyingxiuluo commented
> 新增站点 https://javday.tv/ 适配国产适配刮削

这个javday填到国产番号里面，保存后重启软件就没了
![微信截图_20240716093933](https://github.com/user-attachments/assets/d5b2ec45-4744-4121-83b4-57a68818d323)