修复iqqtv中文，回退并修复google翻译
sqzw-x/mdcx pull request #251
Opened 2024-08-31 10:22 UTC by anyingxiuluo

1. 修复iqqtv中文#246
2. 回退39c358a2f5d4834ec6c4b61b6df2fb9296709271这里修改的google翻译，并修复了bug，解决了因为该修改引入的#250
3. 很少用GIT提交代码，下面有很多不必要的提交不知道怎么删，望见谅

2024-09-07 02:13 UTC, sqzw-x requested changes

2024-09-07 02:13 UTC, sqzw-x commented on src/models/core/web.py
> +            return title, outline, f'返回数据格式异常！返回内容：{response} 错误：{e}'
原来的这种写法可读性为 0, 不要回退. 加一个异常处理即可

2024-09-07 02:22 UTC, anyingxiuluo commented on src/models/core/web.py
> +            return title, outline, f'返回数据格式异常！返回内容：{response} 错误：{e}'
原来的写法标题和内容一起翻译,能减少一次google翻译请求,防止被封

2024-09-08 16:07 UTC, sqzw-x commented on src/models/core/web.py
> +            return title, outline, f'返回数据格式异常！返回内容：{response} 错误：{e}'
Google translate 频率限制很宽松, 没有必要多此一举

2024-09-24 14:35 UTC, sqzw-x approved these changes

2024-09-24 14:38 UTC, merged